const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.join(__dirname,'output');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/');
 await page.waitForSelector('#school-rows tr');
 assert.equal(await page.locator('#school-rows tr').count(),118);
 assert.deepEqual(await page.locator('.metric-number').allTextContents(),['118','115','38','42']);
 assert.equal(await page.locator('[data-point]').count(),114);
 await page.click('#school-toggle');
 assert.equal(await page.locator('#school-options').isVisible(),true);
 await page.locator('[data-school="4361"]').click();
 assert.equal(await page.locator('#school-rows tr').count(),1);
 assert.equal(await page.locator('#school-options').isVisible(),false);
 await page.click('#reset');
 await page.fill('#search','Bates');
 await page.keyboard.press('ArrowDown');
 await page.keyboard.press('ArrowDown');
 await page.keyboard.press('Enter');
 assert.equal(await page.inputValue('#search'),'Bates Elementary School');
 await page.click('#reset');
 assert.equal(await page.locator('#method-content').count(),0);
 await page.getByRole('link',{name:'Data & methodology',exact:true}).click();
 await page.waitForSelector('#method-content .method-grid');
 assert.match(page.url(),/methodology.html/);
 assert.equal(await page.locator('#limitations').count(),1);
 await page.getByRole('link',{name:'Back to the school explorer',exact:false}).click();
 await page.waitForSelector('#school-rows tr');
 assert.equal(await page.locator('#school-rows tr').count(),118);
 assert.equal(await page.locator('.lede').evaluate(e=>getComputedStyle(e).fontSize),'17px');
 await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
 await page.selectOption('#score','missing');
 assert.deepEqual(await page.locator('.metric-number').allTextContents(),['3','0','0','0']);
 assert.equal(await page.locator('[data-point]').count(),0);
 await page.click('#reset');
 await page.selectOption('#neighborhood','East Boston');
 await page.selectOption('#level','Elementary');
 const expected=await page.evaluate(async()=>{const d=await(await fetch('data/schools.json')).json();return d.schools.filter(s=>s.neighborhood==='East Boston'&&s.level==='Elementary').length;});
 assert.equal(await page.locator('#school-rows tr').count(),expected);
 await page.click('#reset');
 await page.fill('#search','zzzz-no-school');
 assert.equal(await page.locator('.metric-number').first().textContent(),'0');
 assert.match(await page.locator('#school-rows').textContent(),/No matching/);
 assert.match(await page.locator('#recommendations').textContent(),/Select school/);
 await page.click('#reset');
 for(let i=0;i<4;i++)await page.locator('[data-select]').nth(i).check();
 // click instead of check: this deliberately rejected fifth selection is unchecked again.
 await page.locator('[data-select]').nth(4).click();
 assert.equal(await page.locator('[data-select]:checked').count(),4);
 await page.click('#compare-button');
 assert.equal(await page.locator('#comparison thead th').count(),5);
 assert.equal(await page.locator('#comparison').isVisible(),true);
 await page.screenshot({path:path.join(output,'comparison.png')});
 await page.fill('#search','Margarita');
 assert.equal(await page.locator('[data-select]:checked').count(),0);
 assert.equal(await page.locator('#comparison').isVisible(),false);
 assert.match(await page.locator('#school-rows').textContent(),/371\*/);
 assert.match(await page.locator('#school-rows').textContent(),/Qualified/);
 await page.click('#reset');
 await page.click('[data-sort="score"]');
 assert.match(await page.locator('#school-rows tr').first().textContent(),/0 \/ 4/);
 assert.match(await page.locator('#school-rows tr').last().textContent(),/Not reported/);
 await page.click('[data-sort="score"]');
 assert.match(await page.locator('#school-rows tr').first().textContent(),/4 \/ 4/);
 assert.match(await page.locator('#school-rows tr').last().textContent(),/Not reported/);
 await page.locator('[data-point]').first().focus();
 await page.keyboard.press('Enter');
 assert.match(await page.locator('#point-detail').textContent(),/Source row/);
 await page.setViewportSize({width:1280,height:800});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(output,'laptop.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 // Check registered tool with a test adapter. Native WebMCP availability is separately reported.
 const nativeWebMCP=await page.evaluate(()=>!!document.modelContext?.registerTool);
 await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.registeredTools[tool.name]=tool;}},configurable:true});});
 await page.reload();await page.waitForFunction(()=>window.registeredTools?.set_school_filters);
 const toolResult=await page.evaluate(()=>window.registeredTools.set_school_filters.execute({search:'Adams'}));
 assert.equal(toolResult.records,1);
 assert.equal(await page.locator('#school-rows tr').count(),1);
 const invalid=await page.evaluate(()=>{try{window.registeredTools.set_school_filters.execute({neighborhood:'UNKNOWN'});return false;}catch{return true;}});
 assert.equal(invalid,true);assert.equal(await page.locator('#school-rows tr').count(),1);
 for(const file of ['data/schools.json','data/bps-facilities-original.csv','data/schools-cleaned.csv','data/sources.json'])assert.equal((await page.request.get('http://127.0.0.1:4173/'+file)).status(),200);
 await page.route('**/data/schools.json',route=>route.fulfill({status:500,body:'unavailable'}));
 await page.reload();await page.waitForSelector('#error:not([hidden])');
 assert.match(await page.locator('#error').textContent(),/could not be loaded/);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log(JSON.stringify({status:'PASS',checks:'Counts, filters, search, missing data, qualified value, 4-record limit, comparison pruning, sort, keyboard points, downloads, empty/error states, 1440px and 1280px layouts',webmcp:nativeWebMCP?'Native API available; execution tested with adapter':'Native API unavailable; registration/valid/invalid paths verified with test adapter',screenshots:output},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
